version: '2'
services:
  web:
    build: .
    environment:
      NODE_ENV: development
    tty: true
    command: npm run test:unit
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0.0
